apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-controller
  namespace: argocd
spec:
  destination:
    namespace: ingress-controller
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/francisco1code/argocd-app-of-app'
    targetRevision: HEAD
    path: ingress-controller/app-of-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: 'https://github.com/francisco1code/argocd-app-of-app'
      targetRevision: HEAD
      path: ingress-controller/namespaces
      directory:
        recurse: true
    - repoURL: 'https://github.com/francisco1code/argocd-app-of-app'
      targetRevision: HEAD
      path: ingress-controller/nginx-1
      helm:
        valueFiles:
          - values.yaml
    - repoURL: 'https://github.com/francisco1code/argocd-app-of-app'
      targetRevision: HEAD
      path: ingress-controller/nginx-2
      helm:
        valueFiles:
          - values.yaml
