replicaCount: 3

postgresql:
  replication:
    enabled: true
  postgresqlPassword: mypassword
  replicationPassword: myreplpassword

pgpool:
  enabled: true
  replicaCount: 2

persistence:
  enabled: true
  storageClass: "standard" # Altere conforme a sua configuração de storage class
  accessModes:
    - ReadWriteOnce
  size: 8Gi